/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegalosRouteImport } from './routes/regalos'
import { Route as PersonalizadosRouteImport } from './routes/personalizados'
import { Route as MostradorRouteImport } from './routes/mostrador'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as CocinaRouteImport } from './routes/cocina'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RepartoIdRouteImport } from './routes/reparto.$id'
import { Route as RegaloIdRouteImport } from './routes/regalo.$id'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminPaquetesRouteImport } from './routes/admin.paquetes'
import { Route as AdminInventarioRouteImport } from './routes/admin.inventario'
import { Route as AdminConfiguracionRouteImport } from './routes/admin.configuracion'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'

const RegalosRoute = RegalosRouteImport.update({
  id: '/regalos',
  path: '/regalos',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizadosRoute = PersonalizadosRouteImport.update({
  id: '/personalizados',
  path: '/personalizados',
  getParentRoute: () => rootRouteImport,
} as any)
const MostradorRoute = MostradorRouteImport.update({
  id: '/mostrador',
  path: '/mostrador',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const CocinaRoute = CocinaRouteImport.update({
  id: '/cocina',
  path: '/cocina',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RepartoIdRoute = RepartoIdRouteImport.update({
  id: '/reparto/$id',
  path: '/reparto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RegaloIdRoute = RegaloIdRouteImport.update({
  id: '/regalo/$id',
  path: '/regalo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaquetesRoute = AdminPaquetesRouteImport.update({
  id: '/paquetes',
  path: '/paquetes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventarioRoute = AdminInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cocina': typeof CocinaRoute
  '/eventos': typeof EventosRoute
  '/mostrador': typeof MostradorRoute
  '/personalizados': typeof PersonalizadosRoute
  '/regalos': typeof RegalosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/inventario': typeof AdminInventarioRoute
  '/admin/paquetes': typeof AdminPaquetesRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/regalo/$id': typeof RegaloIdRoute
  '/reparto/$id': typeof RepartoIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cocina': typeof CocinaRoute
  '/eventos': typeof EventosRoute
  '/mostrador': typeof MostradorRoute
  '/personalizados': typeof PersonalizadosRoute
  '/regalos': typeof RegalosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/inventario': typeof AdminInventarioRoute
  '/admin/paquetes': typeof AdminPaquetesRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/regalo/$id': typeof RegaloIdRoute
  '/reparto/$id': typeof RepartoIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cocina': typeof CocinaRoute
  '/eventos': typeof EventosRoute
  '/mostrador': typeof MostradorRoute
  '/personalizados': typeof PersonalizadosRoute
  '/regalos': typeof RegalosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/inventario': typeof AdminInventarioRoute
  '/admin/paquetes': typeof AdminPaquetesRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/regalo/$id': typeof RegaloIdRoute
  '/reparto/$id': typeof RepartoIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cocina'
    | '/eventos'
    | '/mostrador'
    | '/personalizados'
    | '/regalos'
    | '/admin/clientes'
    | '/admin/configuracion'
    | '/admin/inventario'
    | '/admin/paquetes'
    | '/admin/pedidos'
    | '/pedido/$id'
    | '/regalo/$id'
    | '/reparto/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cocina'
    | '/eventos'
    | '/mostrador'
    | '/personalizados'
    | '/regalos'
    | '/admin/clientes'
    | '/admin/configuracion'
    | '/admin/inventario'
    | '/admin/paquetes'
    | '/admin/pedidos'
    | '/pedido/$id'
    | '/regalo/$id'
    | '/reparto/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cocina'
    | '/eventos'
    | '/mostrador'
    | '/personalizados'
    | '/regalos'
    | '/admin/clientes'
    | '/admin/configuracion'
    | '/admin/inventario'
    | '/admin/paquetes'
    | '/admin/pedidos'
    | '/pedido/$id'
    | '/regalo/$id'
    | '/reparto/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CocinaRoute: typeof CocinaRoute
  EventosRoute: typeof EventosRoute
  MostradorRoute: typeof MostradorRoute
  PersonalizadosRoute: typeof PersonalizadosRoute
  RegalosRoute: typeof RegalosRoute
  PedidoIdRoute: typeof PedidoIdRoute
  RegaloIdRoute: typeof RegaloIdRoute
  RepartoIdRoute: typeof RepartoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/regalos': {
      id: '/regalos'
      path: '/regalos'
      fullPath: '/regalos'
      preLoaderRoute: typeof RegalosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalizados': {
      id: '/personalizados'
      path: '/personalizados'
      fullPath: '/personalizados'
      preLoaderRoute: typeof PersonalizadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mostrador': {
      id: '/mostrador'
      path: '/mostrador'
      fullPath: '/mostrador'
      preLoaderRoute: typeof MostradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cocina': {
      id: '/cocina'
      path: '/cocina'
      fullPath: '/cocina'
      preLoaderRoute: typeof CocinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/reparto/$id': {
      id: '/reparto/$id'
      path: '/reparto/$id'
      fullPath: '/reparto/$id'
      preLoaderRoute: typeof RepartoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regalo/$id': {
      id: '/regalo/$id'
      path: '/regalo/$id'
      fullPath: '/regalo/$id'
      preLoaderRoute: typeof RegaloIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paquetes': {
      id: '/admin/paquetes'
      path: '/paquetes'
      fullPath: '/admin/paquetes'
      preLoaderRoute: typeof AdminPaquetesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventario': {
      id: '/admin/inventario'
      path: '/inventario'
      fullPath: '/admin/inventario'
      preLoaderRoute: typeof AdminInventarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminInventarioRoute: typeof AdminInventarioRoute
  AdminPaquetesRoute: typeof AdminPaquetesRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminInventarioRoute: AdminInventarioRoute,
  AdminPaquetesRoute: AdminPaquetesRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CocinaRoute: CocinaRoute,
  EventosRoute: EventosRoute,
  MostradorRoute: MostradorRoute,
  PersonalizadosRoute: PersonalizadosRoute,
  RegalosRoute: RegalosRoute,
  PedidoIdRoute: PedidoIdRoute,
  RegaloIdRoute: RegaloIdRoute,
  RepartoIdRoute: RepartoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
